### ISSUE TITLE
Tests don't pass on v0.5

### ISSUE THREAD

**Issue by ranjanan** [ivanslapnicar/Arrowhead.jl#7]
The tests in this package do not pass on the latest master: 

```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type DoubleDouble.Double{Float64}
This may have arisen from a call to the constructor DoubleDouble.Double{Float64}(...),
since type constructors fall back to convert methods.
 in promote_op(::Base.#.*, ::Type{DoubleDouble.Double{Float64}}, ::Type{DoubleDouble.Double{Float64}}) at ./number.jl:73
 in .*(::DoubleDouble.Double{Float64}, ::Array{DoubleDouble.Double{Float64},1}) at ./arraymath.jl:71
 in rootsah(::Polynomials.Poly{Int64}, ::Array{Float64,1}) at /Users/ranjan/.julia/v0.5/Arrowhead/src/arrowhead7.jl:68
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /Users/ranjan/.julia/v0.5/Arrowhead/test/runtests.jl, in expression starting on line 218
```

**Comment by ivanslapnicar** [comment]
Thank, I will look into it.


---- Ranjan Anantharaman je napisao ----


The tests in this package do not pass on the latest master:

ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type DoubleDouble.Double{Float64}
This may have arisen from a call to the constructor DoubleDouble.Double{Float64}(...),
since type constructors fall back to convert methods.
 in promote_op(::Base.#.*, ::Type{DoubleDouble.Double{Float64}}, ::Type{DoubleDouble.Double{Float64}}) at ./number.jl:73
 in .*(::DoubleDouble.Double{Float64}, ::Array{DoubleDouble.Double{Float64},1}) at ./arraymath.jl:71
 in rootsah(::Polynomials.Poly{Int64}, ::Array{Float64,1}) at /Users/ranjan/.julia/v0.5/Arrowhead/src/arrowhead7.jl:68
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /Users/ranjan/.julia/v0.5/Arrowhead/test/runtests.jl, in expression starting on line 218


-

**Comment by ivanslapnicar** [comment]
There is a new version now for Julia 1.0+.
